"""
Synthesis Core Module

This module contains the core functionality for the Synthesis component
of the Tekton framework, responsible for executing plans generated by Prometheus.
"""

from .execution_models import (
    ExecutionStage, ExecutionStatus, ExecutionPriority,
    ExecutionResult, ExecutionPlan, ExecutionContext
)
from .execution_step import ExecutionStep
from .execution_engine import ExecutionEngine

# Phase management system
from .phase_models import PhaseStatus
from .phase_manager import PhaseManager
from .phase_executor import PhaseExecutor

__all__ = [
    # Execution engine components
    'ExecutionStage', 
    'ExecutionStatus', 
    'ExecutionPriority',
    'ExecutionResult', 
    'ExecutionPlan', 
    'ExecutionContext',
    'ExecutionStep',
    'ExecutionEngine',
    
    # Phase management components
    'PhaseStatus',
    'PhaseManager',
    'PhaseExecutor'
]