/**
 * Environment variables for Tekton UI
 * AUTO-GENERATED by tekton launcher - DO NOT EDIT MANUALLY
 * Generated at: 2025-07-16T18:05:06
 * 
 * This file is automatically regenerated when Tekton starts.
 * Port values are read from the environment configuration.
 */

console.log('[FILE_TRACE] Loading: env.js');

// Single Port Architecture environment variables - from actual environment
window.HEPHAESTUS_PORT = 8380;  // Hephaestus port
window.ENGRAM_PORT = 8300;      // Engram port
window.HERMES_PORT = 8301;      // Hermes port
window.ERGON_PORT = 8302;       // Ergon port
window.RHETOR_PORT = 8303;      // Rhetor port
window.TERMA_PORT = 8304;       // Terma port
window.ATHENA_PORT = 8305;      // Athena port
window.PROMETHEUS_PORT = 8306;  // Prometheus port
window.HARMONIA_PORT = 8307;    // Harmonia port
window.TELOS_PORT = 8308;       // Telos port
window.SYNTHESIS_PORT = 8309;   // Synthesis port
window.TEKTON_CORE_PORT = 8310; // Tekton Core port
window.METIS_PORT = 8311;       // Metis port
window.APOLLO_PORT = 8312;      // Apollo port
window.BUDGET_PORT = 8313;      // Budget port
window.PENIA_PORT = 8313;       // Penia port (same as budget)
window.SOPHIA_PORT = 8314;      // Sophia port
window.NOESIS_PORT = 8315;      // Noesis port
window.NUMA_PORT = 8316;        // Numa port

// Port base configuration for AI port calculation
window.TEKTON_PORT_BASE = 8300;      // Component port base
window.TEKTON_AI_PORT_BASE = 42000;   // AI port base

// Function to calculate AI port from component port
function getAIPort(componentPort) {
    // AI port = AI_BASE + (component_port - COMPONENT_BASE)
    return window.TEKTON_AI_PORT_BASE + (componentPort - window.TEKTON_PORT_BASE);
}

// AI specialist ports (calculated)
window.NUMA_AI_PORT = getAIPort(window.NUMA_PORT);           // numa-ai port
window.ENGRAM_AI_PORT = getAIPort(window.ENGRAM_PORT);       // engram-ai port
window.HERMES_AI_PORT = getAIPort(window.HERMES_PORT);       // hermes-ai port
window.RHETOR_AI_PORT = getAIPort(window.RHETOR_PORT);       // rhetor-ai port
window.TEKTON_CORE_AI_PORT = getAIPort(window.TEKTON_CORE_PORT); // tekton-core-ai port

// Debug settings
window.TEKTON_DEBUG = 'false';        // Master switch for debug instrumentation
window.TEKTON_LOG_LEVEL = 'INFO';   // Default log level

// Mark that ports are from environment, not defaults
window.PORTS_FROM_ENV = true;
window.TEKTON_ENV_TIMESTAMP = '2025-07-16T18:05:06';

// Function to update port values from server - NO LONGER NEEDED
function updatePortsFromServer() {
    console.log('[ENV] updatePortsFromServer called but ports already loaded from environment');
    console.log('[ENV] TEKTON_CORE_PORT =', window.TEKTON_CORE_PORT);
    console.log('[ENV] Ports were loaded at:', window.TEKTON_ENV_TIMESTAMP);
    
    // Still dispatch event for compatibility
    window.dispatchEvent(new CustomEvent('ports-updated'));
}

// No need to wait for DOMContentLoaded - ports are already correct
console.log('[ENV] Loaded port configuration from tekton launcher');
console.log('[ENV] TEKTON_CORE_PORT =', window.TEKTON_CORE_PORT);
console.log('[ENV] NUMA_PORT =', window.NUMA_PORT);
console.log('[ENV] Environment timestamp:', window.TEKTON_ENV_TIMESTAMP);
