/**
 * Environment variables for Tekton UI
 * AUTO-GENERATED by tekton launcher - DO NOT EDIT MANUALLY
 * Generated at: 2025-07-16T17:26:07
 * 
 * This file is automatically regenerated when Tekton starts.
 * Port values are read from the environment configuration.
 */

console.log('[FILE_TRACE] Loading: env.js');

// Single Port Architecture environment variables - from actual environment
window.HEPHAESTUS_PORT = 8080;  // Hephaestus port
window.ENGRAM_PORT = 8000;      // Engram port
window.HERMES_PORT = 8001;      // Hermes port
window.ERGON_PORT = 8002;       // Ergon port
window.RHETOR_PORT = 8003;      // Rhetor port
window.TERMA_PORT = 8004;       // Terma port
window.ATHENA_PORT = 8005;      // Athena port
window.PROMETHEUS_PORT = 8006;  // Prometheus port
window.HARMONIA_PORT = 8007;    // Harmonia port
window.TELOS_PORT = 8008;       // Telos port
window.SYNTHESIS_PORT = 8009;   // Synthesis port
window.TEKTON_CORE_PORT = 8010; // Tekton Core port
window.METIS_PORT = 8011;       // Metis port
window.APOLLO_PORT = 8012;      // Apollo port
window.BUDGET_PORT = 8013;      // Budget port
window.PENIA_PORT = 8013;       // Penia port (same as budget)
window.SOPHIA_PORT = 8014;      // Sophia port
window.NOESIS_PORT = 8015;      // Noesis port
window.NUMA_PORT = 8016;        // Numa port

// Debug settings
window.TEKTON_DEBUG = 'false';        // Master switch for debug instrumentation
window.TEKTON_LOG_LEVEL = 'INFO';   // Default log level

// Mark that ports are from environment, not defaults
window.PORTS_FROM_ENV = true;
window.TEKTON_ENV_TIMESTAMP = '2025-07-16T17:26:07';

// Function to update port values from server - NO LONGER NEEDED
function updatePortsFromServer() {
    console.log('[ENV] updatePortsFromServer called but ports already loaded from environment');
    console.log('[ENV] TEKTON_CORE_PORT =', window.TEKTON_CORE_PORT);
    console.log('[ENV] Ports were loaded at:', window.TEKTON_ENV_TIMESTAMP);
    
    // Still dispatch event for compatibility
    window.dispatchEvent(new CustomEvent('ports-updated'));
}

// No need to wait for DOMContentLoaded - ports are already correct
console.log('[ENV] Loaded port configuration from tekton launcher');
console.log('[ENV] TEKTON_CORE_PORT =', window.TEKTON_CORE_PORT);
console.log('[ENV] NUMA_PORT =', window.NUMA_PORT);
console.log('[ENV] Environment timestamp:', window.TEKTON_ENV_TIMESTAMP);
