from setuptools import setup, find_packages

setup(
    name="tekton-core",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        # Base requirements (essential for all components)
        "python-dotenv>=1.0.0",
        "pydantic>=2.11.5",
        "pydantic-settings>=2.9.1",
        
        # Web framework requirements
        "fastapi>=0.105.0",
        "uvicorn>=0.24.0",
        "starlette>=0.31.1",
        "websockets>=12.0.0",
        "aiohttp>=3.9.0",
        "httpx>=0.24.0",
        "sse-starlette>=1.6.5",
        "python-multipart>=0.0.6",
        "jinja2>=3.1.0",
        "PyYAML>=6.0",
        "requests>=2.31.0",
        
        # AI/LLM integration
        "anthropic>=0.52.0",
        "openai>=1.1.0",
        "litellm>=1.63.0",
        "tiktoken>=0.9.0",
        "langchain>=0.1.0",
        "langchain-community>=0.0.10",
        "pydantic-ai>=0.0.35",
        "tenacity>=8.2.0",
        "backoff>=2.2.0",
        
        # Vector processing and ML
        "faiss-cpu>=1.7.4",
        "qdrant-client>=1.7.0",
        "sentence-transformers>=2.2.2",
        "torch>=2.0.0",
        "transformers>=4.36.0",
        "numpy>=1.26.0",
        "scipy>=1.13.0",
        "scikit-learn>=1.3.0",
        "huggingface-hub>=0.19.0",
        
        # Data processing
        "pandas>=2.0.0",
        "plotly>=5.18.0",
        "matplotlib>=3.8.0",
        "beautifulsoup4>=4.13.0",
        "lxml>=5.0.0",
        "openpyxl>=3.1.0",
        "nltk>=3.8.0",
        "spacy>=3.7.0",
        
        # Database
        "sqlalchemy>=2.0.0",
        "alembic>=1.12.0",
        "aiosqlite>=0.19.0",
        
        # Utilities
        "click>=8.1.0",
        "typer>=0.9.0",
        "rich>=13.7.0",
        "colorama>=0.4.6",
        "python-decouple>=3.8",
        "pytz>=2023.3",
        "croniter>=2.0.0",
        "asyncio-throttle>=1.0.0",
        "aiofiles>=23.2.0",
        "structlog>=24.1.0",
        "loguru>=0.7.0",
        "prometheus-client>=0.19.0",
        "psutil>=5.9.0",
        
        # Additional component-specific dependencies
        "flask>=2.3.0",
        "flask-wtf>=1.2.0",
        "bootstrap-flask>=2.3.0",
        "streamlit>=1.31.0",
        "networkx>=2.6.3",
        "py2neo>=2021.2.0",
        "neo4j>=5.0.0",
        "GitPython>=3.1.30",
        "PyGithub>=2.1.1",
        "watchdog>=3.0.0",
        "python-dateutil>=2.8.0",
        "python-jose[cryptography]>=3.3.0",
        "cryptography>=44.0.0",
        "email-validator>=2.0.0",
        "imapclient>=2.3.0",
        "msal>=1.28.0",
        "google-api-python-client>=2.110.0",
        "google-auth-httplib2>=0.1.1",
        "google-auth-oauthlib>=1.1.0",
        "playwright>=1.49.1",
        "browser-use>=0.1.40",
        "fastmcp>=1.0.0",
        "ptyprocess>=0.7.0",
        "py-cpuinfo>=8.0.0",
        "json5>=0.9.6",
        "cssselect>=1.2.0",
        "seaborn>=0.12.0",
        "tqdm>=4.66.0",
        "Pillow>=11.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
            "flake8>=7.0.0",
            "black>=23.0.0",
            "isort>=5.13.0",
            "mypy>=1.8.0",
            "ipython>=8.18.0",
            "ipdb>=0.13.0",
        ],
        "postgres": [
            "psycopg2-binary>=2.9.0",
        ],
        "mysql": [
            "pymysql>=1.1.0",
        ],
    },
    description="Tekton Core - Comprehensive installation for all Tekton components",
    author="Casey Koons",
    author_email="cskoons@gmail.com",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)