# Tekton Components Configuration
# This is the single source of truth for all Tekton component definitions

components:
  # Core Infrastructure
  tekton_core:
    name: "Tekton Core"
    description: "Core orchestration and startup management"
    category: "infrastructure"
    startup_priority: 6  # Move to end - utility component
    dependencies: []
    
  hermes:
    name: "Hermes"
    description: "Service registry, messaging, and component coordination"
    category: "infrastructure"
    startup_priority: 1
    dependencies: []
    
  # Memory and Knowledge
  engram:
    name: "Engram"
    description: "Persistent memory and knowledge management system"
    category: "memory"
    startup_priority: 2
    dependencies: ["hermes"]
    
  athena:
    name: "Athena"
    description: "Knowledge graph and relationship management"
    category: "knowledge"
    startup_priority: 3
    dependencies: ["hermes", "engram"]
    
  # AI and Intelligence
  rhetor:
    name: "Rhetor"
    description: "Multi-provider LLM orchestration and management"
    category: "ai"
    startup_priority: 3
    dependencies: ["hermes", "engram"]
    capabilities:
      - "llm_orchestration"
      - "multi_provider_support"
      - "intelligent_routing"
      - "context_management"
    
  sophia:
    name: "Sophia"
    description: "Machine learning and system intelligence measurement"
    category: "ai"
    startup_priority: 4
    dependencies: ["hermes"]
    capabilities:
      - "intelligence_measurement"
      - "component_health_monitoring"
      - "ml_analysis"
      
  apollo:
    name: "Apollo"
    description: "Local attention and prediction system"
    category: "ai"
    startup_priority: 4
    dependencies: ["hermes", "rhetor"]
    
  numa:
    name: "Numa"
    description: "Platform AI mentor providing guidance and oversight"
    category: "ai"
    startup_priority: 6  # Starts after all components for platform-wide view
    dependencies: ["hermes", "rhetor"]
    capabilities:
      - "companion_chat"
      - "team_chat"
      - "platform_guidance"
      - "component_mentoring"
    
  noesis:
    name: "Noesis"
    description: "Discovery system for pattern recognition and insights"
    category: "ai"
    startup_priority: 5  # Starts after core AI components
    dependencies: ["hermes", "rhetor", "athena"]
    capabilities:
      - "discovery_chat"
      - "team_chat"
      - "pattern_recognition"
      - "insight_generation"
    
  # Planning and Execution
  prometheus:
    name: "Prometheus"
    description: "Strategic planning and goal management"
    category: "planning"
    startup_priority: 4
    dependencies: ["hermes", "telos"]
    
  telos:
    name: "Telos"
    description: "Requirements tracking and validation"
    category: "planning"
    startup_priority: 3
    dependencies: ["hermes"]
    
  metis:
    name: "Metis"
    description: "Task breakdown and management"
    category: "planning"
    startup_priority: 4
    dependencies: ["hermes", "telos"]
    
  # Workflow and Execution
  harmonia:
    name: "Harmonia"
    description: "Workflow orchestration and state management"
    category: "workflow"
    startup_priority: 4
    dependencies: ["hermes"]
    
  synthesis:
    name: "Synthesis"
    description: "Code synthesis and execution engine"
    category: "execution"
    startup_priority: 5
    dependencies: ["hermes", "harmonia"]
    
  ergon:
    name: "Ergon"
    description: "Agent system for specialized task execution"
    category: "execution"
    startup_priority: 4
    dependencies: ["hermes", "engram"]
    
  # Resource Management
  penia:
    name: "Penia"
    description: "Token usage and cost management"
    category: "resources"
    startup_priority: 3
    dependencies: ["hermes"]
    capabilities:
      - "budget_allocation"
      - "cost_tracking"
      - "assistant_service"
    
  # User Interface
  hephaestus:
    name: "Hephaestus"
    description: "Web-based user interface"
    category: "ui"
    startup_priority: 5
    dependencies: ["hermes"]
    
  terma:
    name: "Terma"
    description: "Terminal interface and command execution"
    category: "ui"
    startup_priority: 5
    dependencies: ["hermes"]
    
# Specialized Services (not primary components)
services: {}
  # LLMAdapter removed - use Rhetor (port 8003) with tekton-llm-client instead
  # terma_ws removed - WebSocket functionality integrated into main Terma component
