version: '3.8'

services:
  ergon:
    build:
      context: .
    ports:
      - "8501:8501"  # Streamlit UI
      - "8000:8000"  # API (when enabled)
    volumes:
      - ergon-data:/data
      - .env:/app/.env:ro
      - .env.owner:/app/.env.owner:ro
    command: ui
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ergon-data:
